site_name: Hdrnnf Docs 
theme:
  logo: img/zoyy.png
  favicon: img/zoyy.png
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    logo: material/library-shelves
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.expand
    - navigation.path
    - navigation.tops
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/eye
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/eye-outline
        name: Switch to system preference

markdown_extensions:
  - attr_list
        
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/hdrnnf
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/frlhdrn/
copyright: Copyright &copy; 2023 Hdrnnf